version: "3.8"
services:
  db:
    image: mysql:8.3.0
    command: >
      --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${NEXT_PORT}:3000
    restart: always
    environment:
      - VITE_PORT=${NEXT_PORT}
      - VITE_FOAL_URL=${URL_HOST}
      - VITE_FOAL_PORT=${PORT_BACKEND}
      - NEXT_PUBLIC_NO_ERROR_DISPLAY=true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ && npm run build && npm run start"

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    ports:
      - ${PORT_BACKEND}:5000
    environment:
      - DB_HOST=${DB_HOST_BACK}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - URL_HOST_REDIRECT=${URL_HOST_REDIRECT}
      - URL_HOST=${URL_HOST}
      - PORT=${PORT_BACKEND}
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    command: >
      sh -c "yarn && npm run build && npm run migrations && npm run dev"

  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - ${PORT_NGINX}:80

  adminer:
    image: adminer
    restart: always
    ports:
      - ${PORT_ADMINER}:8080
